// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package simplechat is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	User
	ChatMsg
*/
package simplechat

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Events int32

const (
	Events_USERJOIN  Events = 1
	Events_USERLEAVE Events = 2
	Events_MESSAGE   Events = 3
)

var Events_name = map[int32]string{
	1: "USERJOIN",
	2: "USERLEAVE",
	3: "MESSAGE",
}
var Events_value = map[string]int32{
	"USERJOIN":  1,
	"USERLEAVE": 2,
	"MESSAGE":   3,
}

func (x Events) Enum() *Events {
	p := new(Events)
	*p = x
	return p
}
func (x Events) String() string {
	return proto.EnumName(Events_name, int32(x))
}
func (x *Events) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Events_value, data, "Events")
	if err != nil {
		return err
	}
	*x = Events(value)
	return nil
}

type User struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type ChatMsg struct {
	From             *string `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Msg              *string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatMsg) Reset()         { *m = ChatMsg{} }
func (m *ChatMsg) String() string { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()    {}

func (m *ChatMsg) GetFrom() string {
	if m != nil && m.From != nil {
		return *m.From
	}
	return ""
}

func (m *ChatMsg) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("simplechat.Events", Events_name, Events_value)
}
